### ISSUE TITLE
Dependency missing?

### ISSUE THREAD

**Issue by nickbalestra** [northbrookjs/eslint#55]
Hi Tylor,

I guess there might be a dependency missing [here](https://github.com/northbrookjs/eslint/blob/master/lib/index.js#L3) ?

**Comment by TylorS** [comment]
Hey, thanks for the issue. It looks I screwed up on my end for sure.
I actually neglected to build the new `src/` folder into the `lib/` folder and publish the correct thing :smile: 

Fix incoming

**Comment by TylorS** [comment]
Okay, hopefully fixed in v2.0.1. Let me know if it solves that specific issue at least.

**Comment by nickbalestra** [comment]
Sure and thank you!

**Comment by nickbalestra** [comment]
Yes, that solves it. I Still have some issue updating create-cycle-app to latest northbrook, especially related to the `release --check` command throwing an error. I'll investigate it further and open an issue on `NB`.

Many thanks again!
